name: aws-deploy-preview
on:
  workflow_dispatch:
  push:
    branches:
      - preview

jobs:
  deploy:
    uses: ./.github/workflows/aws-deploy-common.yml
    with:
      cdk_env_name: dev
      env_name: preview
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
