name: aws-deploy-production
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/aws-deploy-common.yml
    with:
      cdk_env_name: prod
      env_name: production
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
